/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserXSykDataResponseDto,
} from '../models/index';
import {
    UserXSykDataResponseDtoFromJSON,
    UserXSykDataResponseDtoToJSON,
} from '../models/index';

export interface VestPositionsControllerGetUserDataRequest {
    chainId: VestPositionsControllerGetUserDataChainIdEnum;
    account: string;
}

/**
 * 
 */
export class XSYKApi extends runtime.BaseAPI {

    /**
     */
    async vestPositionsControllerGetUserDataRaw(requestParameters: VestPositionsControllerGetUserDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserXSykDataResponseDto>>> {
        if (requestParameters['chainId'] == null) {
            throw new runtime.RequiredError(
                'chainId',
                'Required parameter "chainId" was null or undefined when calling vestPositionsControllerGetUserData().'
            );
        }

        if (requestParameters['account'] == null) {
            throw new runtime.RequiredError(
                'account',
                'Required parameter "account" was null or undefined when calling vestPositionsControllerGetUserData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chainId'] != null) {
            queryParameters['chainId'] = requestParameters['chainId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/xsyk/vest-positions/{account}`.replace(`{${"account"}}`, encodeURIComponent(String(requestParameters['account']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserXSykDataResponseDtoFromJSON));
    }

    /**
     */
    async vestPositionsControllerGetUserData(requestParameters: VestPositionsControllerGetUserDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserXSykDataResponseDto>> {
        const response = await this.vestPositionsControllerGetUserDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const VestPositionsControllerGetUserDataChainIdEnum = {
    NUMBER_5000: 5000,
    NUMBER_42161: 42161
} as const;
export type VestPositionsControllerGetUserDataChainIdEnum = typeof VestPositionsControllerGetUserDataChainIdEnum[keyof typeof VestPositionsControllerGetUserDataChainIdEnum];
