/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepositResponseDtoReservedWithdrawable
 */
export interface DepositResponseDtoReservedWithdrawable {
    /**
     * Amount of token0
     * @type {string}
     * @memberof DepositResponseDtoReservedWithdrawable
     */
    token0: string;
    /**
     * Amount of token1
     * @type {string}
     * @memberof DepositResponseDtoReservedWithdrawable
     */
    token1: string;
    /**
     * 
     * @type {string}
     * @memberof DepositResponseDtoReservedWithdrawable
     */
    readonly liquidity: string;
}

/**
 * Check if a given object implements the DepositResponseDtoReservedWithdrawable interface.
 */
export function instanceOfDepositResponseDtoReservedWithdrawable(value: object): value is DepositResponseDtoReservedWithdrawable {
    if (!('token0' in value) || value['token0'] === undefined) return false;
    if (!('token1' in value) || value['token1'] === undefined) return false;
    if (!('liquidity' in value) || value['liquidity'] === undefined) return false;
    return true;
}

export function DepositResponseDtoReservedWithdrawableFromJSON(json: any): DepositResponseDtoReservedWithdrawable {
    return DepositResponseDtoReservedWithdrawableFromJSONTyped(json, false);
}

export function DepositResponseDtoReservedWithdrawableFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositResponseDtoReservedWithdrawable {
    if (json == null) {
        return json;
    }
    return {
        
        'token0': json['token0'],
        'token1': json['token1'],
        'liquidity': json['liquidity'],
    };
}

export function DepositResponseDtoReservedWithdrawableToJSON(json: any): DepositResponseDtoReservedWithdrawable {
    return DepositResponseDtoReservedWithdrawableToJSONTyped(json, false);
}

export function DepositResponseDtoReservedWithdrawableToJSONTyped(value?: Omit<DepositResponseDtoReservedWithdrawable, 'liquidity'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token0': value['token0'],
        'token1': value['token1'],
    };
}

