/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepositResponseDtoReservedWithdrawable } from './DepositResponseDtoReservedWithdrawable';
import {
    DepositResponseDtoReservedWithdrawableFromJSON,
    DepositResponseDtoReservedWithdrawableFromJSONTyped,
    DepositResponseDtoReservedWithdrawableToJSON,
    DepositResponseDtoReservedWithdrawableToJSONTyped,
} from './DepositResponseDtoReservedWithdrawable';

/**
 * 
 * @export
 * @interface DepositResponseDtoReserved
 */
export interface DepositResponseDtoReserved {
    /**
     * Amount of token0
     * @type {string}
     * @memberof DepositResponseDtoReserved
     */
    token0: string;
    /**
     * Amount of token1
     * @type {string}
     * @memberof DepositResponseDtoReserved
     */
    token1: string;
    /**
     * 
     * @type {DepositResponseDtoReservedWithdrawable}
     * @memberof DepositResponseDtoReserved
     */
    readonly withdrawable: DepositResponseDtoReservedWithdrawable;
    /**
     * 
     * @type {number}
     * @memberof DepositResponseDtoReserved
     */
    readonly lastReserve: number;
}

/**
 * Check if a given object implements the DepositResponseDtoReserved interface.
 */
export function instanceOfDepositResponseDtoReserved(value: object): value is DepositResponseDtoReserved {
    if (!('token0' in value) || value['token0'] === undefined) return false;
    if (!('token1' in value) || value['token1'] === undefined) return false;
    if (!('withdrawable' in value) || value['withdrawable'] === undefined) return false;
    if (!('lastReserve' in value) || value['lastReserve'] === undefined) return false;
    return true;
}

export function DepositResponseDtoReservedFromJSON(json: any): DepositResponseDtoReserved {
    return DepositResponseDtoReservedFromJSONTyped(json, false);
}

export function DepositResponseDtoReservedFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositResponseDtoReserved {
    if (json == null) {
        return json;
    }
    return {
        
        'token0': json['token0'],
        'token1': json['token1'],
        'withdrawable': DepositResponseDtoReservedWithdrawableFromJSON(json['withdrawable']),
        'lastReserve': json['lastReserve'],
    };
}

export function DepositResponseDtoReservedToJSON(json: any): DepositResponseDtoReserved {
    return DepositResponseDtoReservedToJSONTyped(json, false);
}

export function DepositResponseDtoReservedToJSONTyped(value?: Omit<DepositResponseDtoReserved, 'withdrawable'|'lastReserve'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token0': value['token0'],
        'token1': value['token1'],
    };
}

