/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiquidityToken0Token1 } from './LiquidityToken0Token1';
import {
    LiquidityToken0Token1FromJSON,
    LiquidityToken0Token1FromJSONTyped,
    LiquidityToken0Token1ToJSON,
    LiquidityToken0Token1ToJSONTyped,
} from './LiquidityToken0Token1';
import type { HandlerMeta } from './HandlerMeta';
import {
    HandlerMetaFromJSON,
    HandlerMetaFromJSONTyped,
    HandlerMetaToJSON,
    HandlerMetaToJSONTyped,
} from './HandlerMeta';
import type { Token0Token1 } from './Token0Token1';
import {
    Token0Token1FromJSON,
    Token0Token1FromJSONTyped,
    Token0Token1ToJSON,
    Token0Token1ToJSONTyped,
} from './Token0Token1';
import type { Strikes } from './Strikes';
import {
    StrikesFromJSON,
    StrikesFromJSONTyped,
    StrikesToJSON,
    StrikesToJSONTyped,
} from './Strikes';

/**
 * 
 * @export
 * @interface DepositHistoryResponseDto
 */
export interface DepositHistoryResponseDto {
    /**
     * 
     * @type {Strikes}
     * @memberof DepositHistoryResponseDto
     */
    readonly strikes: Strikes;
    /**
     * 
     * @type {string}
     * @memberof DepositHistoryResponseDto
     */
    readonly txHash: string;
    /**
     * 
     * @type {number}
     * @memberof DepositHistoryResponseDto
     */
    readonly timestamp: number;
    /**
     * 
     * @type {LiquidityToken0Token1}
     * @memberof DepositHistoryResponseDto
     */
    readonly liquidity: LiquidityToken0Token1;
    /**
     * 
     * @type {Token0Token1}
     * @memberof DepositHistoryResponseDto
     */
    readonly tokens: Token0Token1;
    /**
     * 
     * @type {HandlerMeta}
     * @memberof DepositHistoryResponseDto
     */
    readonly handler: HandlerMeta;
}

/**
 * Check if a given object implements the DepositHistoryResponseDto interface.
 */
export function instanceOfDepositHistoryResponseDto(value: object): value is DepositHistoryResponseDto {
    if (!('strikes' in value) || value['strikes'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('liquidity' in value) || value['liquidity'] === undefined) return false;
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    if (!('handler' in value) || value['handler'] === undefined) return false;
    return true;
}

export function DepositHistoryResponseDtoFromJSON(json: any): DepositHistoryResponseDto {
    return DepositHistoryResponseDtoFromJSONTyped(json, false);
}

export function DepositHistoryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositHistoryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'strikes': StrikesFromJSON(json['strikes']),
        'txHash': json['txHash'],
        'timestamp': json['timestamp'],
        'liquidity': LiquidityToken0Token1FromJSON(json['liquidity']),
        'tokens': Token0Token1FromJSON(json['tokens']),
        'handler': HandlerMetaFromJSON(json['handler']),
    };
}

export function DepositHistoryResponseDtoToJSON(json: any): DepositHistoryResponseDto {
    return DepositHistoryResponseDtoToJSONTyped(json, false);
}

export function DepositHistoryResponseDtoToJSONTyped(value?: Omit<DepositHistoryResponseDto, 'strikes'|'txHash'|'timestamp'|'liquidity'|'tokens'|'handler'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

