/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenDto } from './TokenDto';
import {
    TokenDtoFromJSON,
    TokenDtoFromJSONTyped,
    TokenDtoToJSON,
    TokenDtoToJSONTyped,
} from './TokenDto';

/**
 * 
 * @export
 * @interface ExerciseHistoryResponseDto
 */
export interface ExerciseHistoryResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly strike: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly exercisePrice: number;
    /**
     * 
     * @type {string}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly premium: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly timestamp: string;
    /**
     * 
     * @type {number}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly ttl: number;
    /**
     * 
     * @type {string}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly type: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly profit: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly size: string;
    /**
     * 
     * @type {TokenDto}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly sizeToken: TokenDto;
    /**
     * 
     * @type {TokenDto}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly profitToken: TokenDto;
    /**
     * 
     * @type {string}
     * @memberof ExerciseHistoryResponseDto
     */
    readonly txHash: string;
}

/**
 * Check if a given object implements the ExerciseHistoryResponseDto interface.
 */
export function instanceOfExerciseHistoryResponseDto(value: object): value is ExerciseHistoryResponseDto {
    if (!('strike' in value) || value['strike'] === undefined) return false;
    if (!('exercisePrice' in value) || value['exercisePrice'] === undefined) return false;
    if (!('premium' in value) || value['premium'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('ttl' in value) || value['ttl'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('profit' in value) || value['profit'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('sizeToken' in value) || value['sizeToken'] === undefined) return false;
    if (!('profitToken' in value) || value['profitToken'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    return true;
}

export function ExerciseHistoryResponseDtoFromJSON(json: any): ExerciseHistoryResponseDto {
    return ExerciseHistoryResponseDtoFromJSONTyped(json, false);
}

export function ExerciseHistoryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseHistoryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'strike': json['strike'],
        'exercisePrice': json['exercisePrice'],
        'premium': json['premium'],
        'timestamp': json['timestamp'],
        'ttl': json['ttl'],
        'type': json['type'],
        'profit': json['profit'],
        'size': json['size'],
        'sizeToken': TokenDtoFromJSON(json['sizeToken']),
        'profitToken': TokenDtoFromJSON(json['profitToken']),
        'txHash': json['txHash'],
    };
}

export function ExerciseHistoryResponseDtoToJSON(json: any): ExerciseHistoryResponseDto {
    return ExerciseHistoryResponseDtoToJSONTyped(json, false);
}

export function ExerciseHistoryResponseDtoToJSONTyped(value?: Omit<ExerciseHistoryResponseDto, 'strike'|'exercisePrice'|'premium'|'timestamp'|'ttl'|'type'|'profit'|'size'|'sizeToken'|'profitToken'|'txHash'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

