/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeesResponseDto
 */
export interface FeesResponseDto {
    /**
     * 
     * @type {number}
     * @memberof FeesResponseDto
     */
    readonly premiums: number;
    /**
     * 
     * @type {number}
     * @memberof FeesResponseDto
     */
    readonly protocolFees: number;
}

/**
 * Check if a given object implements the FeesResponseDto interface.
 */
export function instanceOfFeesResponseDto(value: object): value is FeesResponseDto {
    if (!('premiums' in value) || value['premiums'] === undefined) return false;
    if (!('protocolFees' in value) || value['protocolFees'] === undefined) return false;
    return true;
}

export function FeesResponseDtoFromJSON(json: any): FeesResponseDto {
    return FeesResponseDtoFromJSONTyped(json, false);
}

export function FeesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'premiums': json['premiums'],
        'protocolFees': json['protocolFees'],
    };
}

export function FeesResponseDtoToJSON(json: any): FeesResponseDto {
    return FeesResponseDtoToJSONTyped(json, false);
}

export function FeesResponseDtoToJSONTyped(value?: Omit<FeesResponseDto, 'premiums'|'protocolFees'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

