/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlerMeta
 */
export interface HandlerMeta {
    /**
     * 
     * @type {string}
     * @memberof HandlerMeta
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof HandlerMeta
     */
    deprecated: boolean;
    /**
     * 
     * @type {object}
     * @memberof HandlerMeta
     */
    handler: object;
    /**
     * 
     * @type {string}
     * @memberof HandlerMeta
     */
    pool: string;
}

/**
 * Check if a given object implements the HandlerMeta interface.
 */
export function instanceOfHandlerMeta(value: object): value is HandlerMeta {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('deprecated' in value) || value['deprecated'] === undefined) return false;
    if (!('handler' in value) || value['handler'] === undefined) return false;
    if (!('pool' in value) || value['pool'] === undefined) return false;
    return true;
}

export function HandlerMetaFromJSON(json: any): HandlerMeta {
    return HandlerMetaFromJSONTyped(json, false);
}

export function HandlerMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlerMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'deprecated': json['deprecated'],
        'handler': json['handler'],
        'pool': json['pool'],
    };
}

export function HandlerMetaToJSON(json: any): HandlerMeta {
    return HandlerMetaToJSONTyped(json, false);
}

export function HandlerMetaToJSONTyped(value?: HandlerMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'deprecated': value['deprecated'],
        'handler': value['handler'],
        'pool': value['pool'],
    };
}

