/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiquidityToken0Token1
 */
export interface LiquidityToken0Token1 {
    /**
     * Amount of token0 provided as liquidity
     * @type {string}
     * @memberof LiquidityToken0Token1
     */
    amount0: string;
    /**
     * Amount of token1 provided as liquidity
     * @type {string}
     * @memberof LiquidityToken0Token1
     */
    amount1: string;
}

/**
 * Check if a given object implements the LiquidityToken0Token1 interface.
 */
export function instanceOfLiquidityToken0Token1(value: object): value is LiquidityToken0Token1 {
    if (!('amount0' in value) || value['amount0'] === undefined) return false;
    if (!('amount1' in value) || value['amount1'] === undefined) return false;
    return true;
}

export function LiquidityToken0Token1FromJSON(json: any): LiquidityToken0Token1 {
    return LiquidityToken0Token1FromJSONTyped(json, false);
}

export function LiquidityToken0Token1FromJSONTyped(json: any, ignoreDiscriminator: boolean): LiquidityToken0Token1 {
    if (json == null) {
        return json;
    }
    return {
        
        'amount0': json['amount0'],
        'amount1': json['amount1'],
    };
}

export function LiquidityToken0Token1ToJSON(json: any): LiquidityToken0Token1 {
    return LiquidityToken0Token1ToJSONTyped(json, false);
}

export function LiquidityToken0Token1ToJSONTyped(value?: LiquidityToken0Token1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount0': value['amount0'],
        'amount1': value['amount1'],
    };
}

