/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenDto } from './TokenDto';
import {
    TokenDtoFromJSON,
    TokenDtoFromJSONTyped,
    TokenDtoToJSON,
    TokenDtoToJSONTyped,
} from './TokenDto';

/**
 * 
 * @export
 * @interface OptionMarketsResponseDtoV2
 */
export interface OptionMarketsResponseDtoV2 {
    /**
     * 
     * @type {boolean}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly deprecated: boolean;
    /**
     * 
     * @type {string}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly address: string;
    /**
     * 
     * @type {TokenDto}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly callToken: TokenDto;
    /**
     * 
     * @type {TokenDto}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly putToken: TokenDto;
    /**
     * 
     * @type {string}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly primePool: string;
    /**
     * 
     * @type {string}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly optionsPricing: string;
    /**
     * 
     * @type {string}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly tokenURIFetcher: string;
    /**
     * 
     * @type {string}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly pairName: string;
    /**
     * 
     * @type {string}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly ticker: string;
    /**
     * 
     * @type {number}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly chainId: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly pools: Array<object>;
    /**
     * 
     * @type {object}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly feeStrategy: object;
    /**
     * 
     * @type {number}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly premiums24h: number;
    /**
     * 
     * @type {number}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly volume24h: number;
    /**
     * 
     * @type {number}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly protocolFees24h: number;
    /**
     * 
     * @type {number}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly totalLiquidity: number;
    /**
     * 
     * @type {number}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly availableLiquidity: number;
    /**
     * 
     * @type {number}
     * @memberof OptionMarketsResponseDtoV2
     */
    readonly openInterest: number;
}

/**
 * Check if a given object implements the OptionMarketsResponseDtoV2 interface.
 */
export function instanceOfOptionMarketsResponseDtoV2(value: object): value is OptionMarketsResponseDtoV2 {
    if (!('deprecated' in value) || value['deprecated'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('callToken' in value) || value['callToken'] === undefined) return false;
    if (!('putToken' in value) || value['putToken'] === undefined) return false;
    if (!('primePool' in value) || value['primePool'] === undefined) return false;
    if (!('optionsPricing' in value) || value['optionsPricing'] === undefined) return false;
    if (!('tokenURIFetcher' in value) || value['tokenURIFetcher'] === undefined) return false;
    if (!('pairName' in value) || value['pairName'] === undefined) return false;
    if (!('ticker' in value) || value['ticker'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('pools' in value) || value['pools'] === undefined) return false;
    if (!('feeStrategy' in value) || value['feeStrategy'] === undefined) return false;
    if (!('premiums24h' in value) || value['premiums24h'] === undefined) return false;
    if (!('volume24h' in value) || value['volume24h'] === undefined) return false;
    if (!('protocolFees24h' in value) || value['protocolFees24h'] === undefined) return false;
    if (!('totalLiquidity' in value) || value['totalLiquidity'] === undefined) return false;
    if (!('availableLiquidity' in value) || value['availableLiquidity'] === undefined) return false;
    if (!('openInterest' in value) || value['openInterest'] === undefined) return false;
    return true;
}

export function OptionMarketsResponseDtoV2FromJSON(json: any): OptionMarketsResponseDtoV2 {
    return OptionMarketsResponseDtoV2FromJSONTyped(json, false);
}

export function OptionMarketsResponseDtoV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionMarketsResponseDtoV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'deprecated': json['deprecated'],
        'address': json['address'],
        'callToken': TokenDtoFromJSON(json['callToken']),
        'putToken': TokenDtoFromJSON(json['putToken']),
        'primePool': json['primePool'],
        'optionsPricing': json['optionsPricing'],
        'tokenURIFetcher': json['tokenURIFetcher'],
        'pairName': json['pairName'],
        'ticker': json['ticker'],
        'chainId': json['chainId'],
        'pools': json['pools'],
        'feeStrategy': json['feeStrategy'],
        'premiums24h': json['premiums24h'],
        'volume24h': json['volume24h'],
        'protocolFees24h': json['protocolFees24h'],
        'totalLiquidity': json['totalLiquidity'],
        'availableLiquidity': json['availableLiquidity'],
        'openInterest': json['openInterest'],
    };
}

export function OptionMarketsResponseDtoV2ToJSON(json: any): OptionMarketsResponseDtoV2 {
    return OptionMarketsResponseDtoV2ToJSONTyped(json, false);
}

export function OptionMarketsResponseDtoV2ToJSONTyped(value?: Omit<OptionMarketsResponseDtoV2, 'deprecated'|'address'|'callToken'|'putToken'|'primePool'|'optionsPricing'|'tokenURIFetcher'|'pairName'|'ticker'|'chainId'|'pools'|'feeStrategy'|'premiums24h'|'volume24h'|'protocolFees24h'|'totalLiquidity'|'availableLiquidity'|'openInterest'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

