/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PnlDeltaResponseDto
 */
export interface PnlDeltaResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PnlDeltaResponseDto
     */
    readonly delta: number;
    /**
     * 
     * @type {number}
     * @memberof PnlDeltaResponseDto
     */
    readonly timestamp: number;
}

/**
 * Check if a given object implements the PnlDeltaResponseDto interface.
 */
export function instanceOfPnlDeltaResponseDto(value: object): value is PnlDeltaResponseDto {
    if (!('delta' in value) || value['delta'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PnlDeltaResponseDtoFromJSON(json: any): PnlDeltaResponseDto {
    return PnlDeltaResponseDtoFromJSONTyped(json, false);
}

export function PnlDeltaResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PnlDeltaResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'delta': json['delta'],
        'timestamp': json['timestamp'],
    };
}

export function PnlDeltaResponseDtoToJSON(json: any): PnlDeltaResponseDto {
    return PnlDeltaResponseDtoToJSONTyped(json, false);
}

export function PnlDeltaResponseDtoToJSONTyped(value?: Omit<PnlDeltaResponseDto, 'delta'|'timestamp'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

