/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionData } from './TransactionData';
import {
    TransactionDataFromJSON,
    TransactionDataFromJSONTyped,
    TransactionDataToJSON,
    TransactionDataToJSONTyped,
} from './TransactionData';

/**
 * 
 * @export
 * @interface PrepareExerciseResponseDto
 */
export interface PrepareExerciseResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PrepareExerciseResponseDto
     */
    readonly profit: string;
    /**
     * 
     * @type {string}
     * @memberof PrepareExerciseResponseDto
     */
    readonly token: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PrepareExerciseResponseDto
     */
    readonly swapData: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PrepareExerciseResponseDto
     */
    readonly swappers: Array<string>;
    /**
     * 
     * @type {TransactionData}
     * @memberof PrepareExerciseResponseDto
     */
    readonly tx: TransactionData;
}

/**
 * Check if a given object implements the PrepareExerciseResponseDto interface.
 */
export function instanceOfPrepareExerciseResponseDto(value: object): value is PrepareExerciseResponseDto {
    if (!('profit' in value) || value['profit'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('swapData' in value) || value['swapData'] === undefined) return false;
    if (!('swappers' in value) || value['swappers'] === undefined) return false;
    if (!('tx' in value) || value['tx'] === undefined) return false;
    return true;
}

export function PrepareExerciseResponseDtoFromJSON(json: any): PrepareExerciseResponseDto {
    return PrepareExerciseResponseDtoFromJSONTyped(json, false);
}

export function PrepareExerciseResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareExerciseResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'profit': json['profit'],
        'token': json['token'],
        'swapData': json['swapData'],
        'swappers': json['swappers'],
        'tx': TransactionDataFromJSON(json['tx']),
    };
}

export function PrepareExerciseResponseDtoToJSON(json: any): PrepareExerciseResponseDto {
    return PrepareExerciseResponseDtoToJSONTyped(json, false);
}

export function PrepareExerciseResponseDtoToJSONTyped(value?: Omit<PrepareExerciseResponseDto, 'profit'|'token'|'swapData'|'swappers'|'tx'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

