/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntersectionAmountTokenDto } from './IntersectionAmountTokenDto';
import {
    IntersectionAmountTokenDtoFromJSON,
    IntersectionAmountTokenDtoFromJSONTyped,
    IntersectionAmountTokenDtoToJSON,
    IntersectionAmountTokenDtoToJSONTyped,
} from './IntersectionAmountTokenDto';

/**
 * 
 * @export
 * @interface PrepareDepositResponseDtoTokens
 */
export interface PrepareDepositResponseDtoTokens {
    /**
     * Call token details and amount
     * @type {IntersectionAmountTokenDto}
     * @memberof PrepareDepositResponseDtoTokens
     */
    callToken: IntersectionAmountTokenDto;
    /**
     * Put token details and amount
     * @type {IntersectionAmountTokenDto}
     * @memberof PrepareDepositResponseDtoTokens
     */
    putToken: IntersectionAmountTokenDto;
}

/**
 * Check if a given object implements the PrepareDepositResponseDtoTokens interface.
 */
export function instanceOfPrepareDepositResponseDtoTokens(value: object): value is PrepareDepositResponseDtoTokens {
    if (!('callToken' in value) || value['callToken'] === undefined) return false;
    if (!('putToken' in value) || value['putToken'] === undefined) return false;
    return true;
}

export function PrepareDepositResponseDtoTokensFromJSON(json: any): PrepareDepositResponseDtoTokens {
    return PrepareDepositResponseDtoTokensFromJSONTyped(json, false);
}

export function PrepareDepositResponseDtoTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareDepositResponseDtoTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'callToken': IntersectionAmountTokenDtoFromJSON(json['callToken']),
        'putToken': IntersectionAmountTokenDtoFromJSON(json['putToken']),
    };
}

export function PrepareDepositResponseDtoTokensToJSON(json: any): PrepareDepositResponseDtoTokens {
    return PrepareDepositResponseDtoTokensToJSONTyped(json, false);
}

export function PrepareDepositResponseDtoTokensToJSONTyped(value?: PrepareDepositResponseDtoTokens | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'callToken': IntersectionAmountTokenDtoToJSON(value['callToken']),
        'putToken': IntersectionAmountTokenDtoToJSON(value['putToken']),
    };
}

