/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionData } from './TransactionData';
import {
    TransactionDataFromJSON,
    TransactionDataFromJSONTyped,
    TransactionDataToJSON,
    TransactionDataToJSONTyped,
} from './TransactionData';
import type { PrepareDepositResponseDtoTokens } from './PrepareDepositResponseDtoTokens';
import {
    PrepareDepositResponseDtoTokensFromJSON,
    PrepareDepositResponseDtoTokensFromJSONTyped,
    PrepareDepositResponseDtoTokensToJSON,
    PrepareDepositResponseDtoTokensToJSONTyped,
} from './PrepareDepositResponseDtoTokens';

/**
 * 
 * @export
 * @interface PrepareDepositResponseDto
 */
export interface PrepareDepositResponseDto {
    /**
     * 
     * @type {TransactionData}
     * @memberof PrepareDepositResponseDto
     */
    readonly tx: TransactionData;
    /**
     * 
     * @type {Array<number>}
     * @memberof PrepareDepositResponseDto
     */
    readonly strikes: Array<number>;
    /**
     * 
     * @type {PrepareDepositResponseDtoTokens}
     * @memberof PrepareDepositResponseDto
     */
    readonly tokens: PrepareDepositResponseDtoTokens;
}

/**
 * Check if a given object implements the PrepareDepositResponseDto interface.
 */
export function instanceOfPrepareDepositResponseDto(value: object): value is PrepareDepositResponseDto {
    if (!('tx' in value) || value['tx'] === undefined) return false;
    if (!('strikes' in value) || value['strikes'] === undefined) return false;
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    return true;
}

export function PrepareDepositResponseDtoFromJSON(json: any): PrepareDepositResponseDto {
    return PrepareDepositResponseDtoFromJSONTyped(json, false);
}

export function PrepareDepositResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareDepositResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tx': TransactionDataFromJSON(json['tx']),
        'strikes': json['strikes'],
        'tokens': PrepareDepositResponseDtoTokensFromJSON(json['tokens']),
    };
}

export function PrepareDepositResponseDtoToJSON(json: any): PrepareDepositResponseDto {
    return PrepareDepositResponseDtoToJSONTyped(json, false);
}

export function PrepareDepositResponseDtoToJSONTyped(value?: Omit<PrepareDepositResponseDto, 'tx'|'strikes'|'tokens'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

