/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenDto } from './TokenDto';
import {
    TokenDtoFromJSON,
    TokenDtoFromJSONTyped,
    TokenDtoToJSON,
    TokenDtoToJSONTyped,
} from './TokenDto';

/**
 * 
 * @export
 * @interface PurchaseHistoryResponseDto
 */
export interface PurchaseHistoryResponseDto {
    /**
     * 
     * @type {object}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly txHash: object;
    /**
     * 
     * @type {number}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly strike: number;
    /**
     * 
     * @type {string}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly size: string;
    /**
     * 
     * @type {number}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly ttl: number;
    /**
     * 
     * @type {string}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly type: PurchaseHistoryResponseDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly premium: string;
    /**
     * 
     * @type {TokenDto}
     * @memberof PurchaseHistoryResponseDto
     */
    readonly token: TokenDto;
}


/**
 * @export
 */
export const PurchaseHistoryResponseDtoTypeEnum = {
    Call: 'call',
    Put: 'put'
} as const;
export type PurchaseHistoryResponseDtoTypeEnum = typeof PurchaseHistoryResponseDtoTypeEnum[keyof typeof PurchaseHistoryResponseDtoTypeEnum];


/**
 * Check if a given object implements the PurchaseHistoryResponseDto interface.
 */
export function instanceOfPurchaseHistoryResponseDto(value: object): value is PurchaseHistoryResponseDto {
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('strike' in value) || value['strike'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('ttl' in value) || value['ttl'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('premium' in value) || value['premium'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function PurchaseHistoryResponseDtoFromJSON(json: any): PurchaseHistoryResponseDto {
    return PurchaseHistoryResponseDtoFromJSONTyped(json, false);
}

export function PurchaseHistoryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseHistoryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'txHash': json['txHash'],
        'timestamp': json['timestamp'],
        'strike': json['strike'],
        'size': json['size'],
        'ttl': json['ttl'],
        'type': json['type'],
        'premium': json['premium'],
        'token': TokenDtoFromJSON(json['token']),
    };
}

export function PurchaseHistoryResponseDtoToJSON(json: any): PurchaseHistoryResponseDto {
    return PurchaseHistoryResponseDtoToJSONTyped(json, false);
}

export function PurchaseHistoryResponseDtoToJSONTyped(value?: Omit<PurchaseHistoryResponseDto, 'txHash'|'timestamp'|'strike'|'size'|'ttl'|'type'|'premium'|'token'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

