/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PurchasePositionMetaHandlerDto
 */
export interface PurchasePositionMetaHandlerDto {
    /**
     * 
     * @type {string}
     * @memberof PurchasePositionMetaHandlerDto
     */
    readonly name: string;
    /**
     * 
     * @type {boolean}
     * @memberof PurchasePositionMetaHandlerDto
     */
    readonly deprecated: boolean;
    /**
     * 
     * @type {object}
     * @memberof PurchasePositionMetaHandlerDto
     */
    readonly handler: object;
    /**
     * 
     * @type {object}
     * @memberof PurchasePositionMetaHandlerDto
     */
    readonly pool: object;
}

/**
 * Check if a given object implements the PurchasePositionMetaHandlerDto interface.
 */
export function instanceOfPurchasePositionMetaHandlerDto(value: object): value is PurchasePositionMetaHandlerDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('deprecated' in value) || value['deprecated'] === undefined) return false;
    if (!('handler' in value) || value['handler'] === undefined) return false;
    if (!('pool' in value) || value['pool'] === undefined) return false;
    return true;
}

export function PurchasePositionMetaHandlerDtoFromJSON(json: any): PurchasePositionMetaHandlerDto {
    return PurchasePositionMetaHandlerDtoFromJSONTyped(json, false);
}

export function PurchasePositionMetaHandlerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchasePositionMetaHandlerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'deprecated': json['deprecated'],
        'handler': json['handler'],
        'pool': json['pool'],
    };
}

export function PurchasePositionMetaHandlerDtoToJSON(json: any): PurchasePositionMetaHandlerDto {
    return PurchasePositionMetaHandlerDtoToJSONTyped(json, false);
}

export function PurchasePositionMetaHandlerDtoToJSONTyped(value?: Omit<PurchasePositionMetaHandlerDto, 'name'|'deprecated'|'handler'|'pool'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

