/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PurchasePositionMetaDto } from './PurchasePositionMetaDto';
import {
    PurchasePositionMetaDtoFromJSON,
    PurchasePositionMetaDtoFromJSONTyped,
    PurchasePositionMetaDtoToJSON,
    PurchasePositionMetaDtoToJSONTyped,
} from './PurchasePositionMetaDto';
import type { TokenDto } from './TokenDto';
import {
    TokenDtoFromJSON,
    TokenDtoFromJSONTyped,
    TokenDtoToJSON,
    TokenDtoToJSONTyped,
} from './TokenDto';

/**
 * 
 * @export
 * @interface PurchasePositionsResponseDto
 */
export interface PurchasePositionsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PurchasePositionsResponseDto
     */
    readonly size: string;
    /**
     * 
     * @type {string}
     * @memberof PurchasePositionsResponseDto
     */
    readonly premium: string;
    /**
     * 
     * @type {number}
     * @memberof PurchasePositionsResponseDto
     */
    readonly strike: number;
    /**
     * 
     * @type {string}
     * @memberof PurchasePositionsResponseDto
     */
    readonly type: PurchasePositionsResponseDtoTypeEnum;
    /**
     * 
     * @type {TokenDto}
     * @memberof PurchasePositionsResponseDto
     */
    readonly token: TokenDto;
    /**
     * 
     * @type {PurchasePositionMetaDto}
     * @memberof PurchasePositionsResponseDto
     */
    readonly meta: PurchasePositionMetaDto;
}


/**
 * @export
 */
export const PurchasePositionsResponseDtoTypeEnum = {
    Call: 'call',
    Put: 'put'
} as const;
export type PurchasePositionsResponseDtoTypeEnum = typeof PurchasePositionsResponseDtoTypeEnum[keyof typeof PurchasePositionsResponseDtoTypeEnum];


/**
 * Check if a given object implements the PurchasePositionsResponseDto interface.
 */
export function instanceOfPurchasePositionsResponseDto(value: object): value is PurchasePositionsResponseDto {
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('premium' in value) || value['premium'] === undefined) return false;
    if (!('strike' in value) || value['strike'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PurchasePositionsResponseDtoFromJSON(json: any): PurchasePositionsResponseDto {
    return PurchasePositionsResponseDtoFromJSONTyped(json, false);
}

export function PurchasePositionsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchasePositionsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'],
        'premium': json['premium'],
        'strike': json['strike'],
        'type': json['type'],
        'token': TokenDtoFromJSON(json['token']),
        'meta': PurchasePositionMetaDtoFromJSON(json['meta']),
    };
}

export function PurchasePositionsResponseDtoToJSON(json: any): PurchasePositionsResponseDto {
    return PurchasePositionsResponseDtoToJSONTyped(json, false);
}

export function PurchasePositionsResponseDtoToJSONTyped(value?: Omit<PurchasePositionsResponseDto, 'size'|'premium'|'strike'|'type'|'token'|'meta'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

