/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenDto } from './TokenDto';
import {
    TokenDtoFromJSON,
    TokenDtoFromJSONTyped,
    TokenDtoToJSON,
    TokenDtoToJSONTyped,
} from './TokenDto';

/**
 * 
 * @export
 * @interface QuoteResponseDto
 */
export interface QuoteResponseDto {
    /**
     * 
     * @type {TokenDto}
     * @memberof QuoteResponseDto
     */
    readonly token: TokenDto;
    /**
     * 
     * @type {string}
     * @memberof QuoteResponseDto
     */
    readonly premium: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteResponseDto
     */
    readonly fees: string;
}

/**
 * Check if a given object implements the QuoteResponseDto interface.
 */
export function instanceOfQuoteResponseDto(value: object): value is QuoteResponseDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('premium' in value) || value['premium'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    return true;
}

export function QuoteResponseDtoFromJSON(json: any): QuoteResponseDto {
    return QuoteResponseDtoFromJSONTyped(json, false);
}

export function QuoteResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuoteResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': TokenDtoFromJSON(json['token']),
        'premium': json['premium'],
        'fees': json['fees'],
    };
}

export function QuoteResponseDtoToJSON(json: any): QuoteResponseDto {
    return QuoteResponseDtoToJSONTyped(json, false);
}

export function QuoteResponseDtoToJSONTyped(value?: Omit<QuoteResponseDto, 'token'|'premium'|'fees'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

