/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StrikesChainMetaDto
 */
export interface StrikesChainMetaDto {
    /**
     * 
     * @type {string}
     * @memberof StrikesChainMetaDto
     */
    readonly hook: string;
    /**
     * 
     * @type {number}
     * @memberof StrikesChainMetaDto
     */
    readonly tickLower: number;
    /**
     * 
     * @type {number}
     * @memberof StrikesChainMetaDto
     */
    readonly tickUpper: number;
    /**
     * 
     * @type {string}
     * @memberof StrikesChainMetaDto
     */
    readonly totalTokenLiquidity: string;
    /**
     * 
     * @type {string}
     * @memberof StrikesChainMetaDto
     */
    readonly availableTokenLiquidity: string;
    /**
     * 
     * @type {string}
     * @memberof StrikesChainMetaDto
     */
    readonly totalLiquidity: string;
    /**
     * 
     * @type {string}
     * @memberof StrikesChainMetaDto
     */
    readonly availableLiquidity: string;
}

/**
 * Check if a given object implements the StrikesChainMetaDto interface.
 */
export function instanceOfStrikesChainMetaDto(value: object): value is StrikesChainMetaDto {
    if (!('hook' in value) || value['hook'] === undefined) return false;
    if (!('tickLower' in value) || value['tickLower'] === undefined) return false;
    if (!('tickUpper' in value) || value['tickUpper'] === undefined) return false;
    if (!('totalTokenLiquidity' in value) || value['totalTokenLiquidity'] === undefined) return false;
    if (!('availableTokenLiquidity' in value) || value['availableTokenLiquidity'] === undefined) return false;
    if (!('totalLiquidity' in value) || value['totalLiquidity'] === undefined) return false;
    if (!('availableLiquidity' in value) || value['availableLiquidity'] === undefined) return false;
    return true;
}

export function StrikesChainMetaDtoFromJSON(json: any): StrikesChainMetaDto {
    return StrikesChainMetaDtoFromJSONTyped(json, false);
}

export function StrikesChainMetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrikesChainMetaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hook': json['hook'],
        'tickLower': json['tickLower'],
        'tickUpper': json['tickUpper'],
        'totalTokenLiquidity': json['totalTokenLiquidity'],
        'availableTokenLiquidity': json['availableTokenLiquidity'],
        'totalLiquidity': json['totalLiquidity'],
        'availableLiquidity': json['availableLiquidity'],
    };
}

export function StrikesChainMetaDtoToJSON(json: any): StrikesChainMetaDto {
    return StrikesChainMetaDtoToJSONTyped(json, false);
}

export function StrikesChainMetaDtoToJSONTyped(value?: Omit<StrikesChainMetaDto, 'hook'|'tickLower'|'tickUpper'|'totalTokenLiquidity'|'availableTokenLiquidity'|'totalLiquidity'|'availableLiquidity'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

