/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StrikesChainMetaDto } from './StrikesChainMetaDto';
import {
    StrikesChainMetaDtoFromJSON,
    StrikesChainMetaDtoFromJSONTyped,
    StrikesChainMetaDtoToJSON,
    StrikesChainMetaDtoToJSONTyped,
} from './StrikesChainMetaDto';
import type { HandlerMeta } from './HandlerMeta';
import {
    HandlerMetaFromJSON,
    HandlerMetaFromJSONTyped,
    HandlerMetaToJSON,
    HandlerMetaToJSONTyped,
} from './HandlerMeta';
import type { TokenDto } from './TokenDto';
import {
    TokenDtoFromJSON,
    TokenDtoFromJSONTyped,
    TokenDtoToJSON,
    TokenDtoToJSONTyped,
} from './TokenDto';

/**
 * 
 * @export
 * @interface StrikesChainDto
 */
export interface StrikesChainDto {
    /**
     * 
     * @type {string}
     * @memberof StrikesChainDto
     */
    readonly totalLiquidity: string;
    /**
     * 
     * @type {string}
     * @memberof StrikesChainDto
     */
    readonly availableLiquidity: string;
    /**
     * 
     * @type {string}
     * @memberof StrikesChainDto
     */
    readonly utilization: string;
    /**
     * 
     * @type {string}
     * @memberof StrikesChainDto
     */
    readonly apr: string;
    /**
     * 
     * @type {HandlerMeta}
     * @memberof StrikesChainDto
     */
    readonly handler: HandlerMeta;
    /**
     * 
     * @type {StrikesChainMetaDto}
     * @memberof StrikesChainDto
     */
    readonly meta: StrikesChainMetaDto;
    /**
     * 
     * @type {TokenDto}
     * @memberof StrikesChainDto
     */
    readonly token: TokenDto;
}

/**
 * Check if a given object implements the StrikesChainDto interface.
 */
export function instanceOfStrikesChainDto(value: object): value is StrikesChainDto {
    if (!('totalLiquidity' in value) || value['totalLiquidity'] === undefined) return false;
    if (!('availableLiquidity' in value) || value['availableLiquidity'] === undefined) return false;
    if (!('utilization' in value) || value['utilization'] === undefined) return false;
    if (!('apr' in value) || value['apr'] === undefined) return false;
    if (!('handler' in value) || value['handler'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function StrikesChainDtoFromJSON(json: any): StrikesChainDto {
    return StrikesChainDtoFromJSONTyped(json, false);
}

export function StrikesChainDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrikesChainDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalLiquidity': json['totalLiquidity'],
        'availableLiquidity': json['availableLiquidity'],
        'utilization': json['utilization'],
        'apr': json['apr'],
        'handler': HandlerMetaFromJSON(json['handler']),
        'meta': StrikesChainMetaDtoFromJSON(json['meta']),
        'token': TokenDtoFromJSON(json['token']),
    };
}

export function StrikesChainDtoToJSON(json: any): StrikesChainDto {
    return StrikesChainDtoToJSONTyped(json, false);
}

export function StrikesChainDtoToJSONTyped(value?: Omit<StrikesChainDto, 'totalLiquidity'|'availableLiquidity'|'utilization'|'apr'|'handler'|'meta'|'token'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

