/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Strikes
 */
export interface Strikes {
    /**
     * Call strike
     * @type {number}
     * @memberof Strikes
     */
    call: number;
    /**
     * Put strike
     * @type {number}
     * @memberof Strikes
     */
    put: number;
}

/**
 * Check if a given object implements the Strikes interface.
 */
export function instanceOfStrikes(value: object): value is Strikes {
    if (!('call' in value) || value['call'] === undefined) return false;
    if (!('put' in value) || value['put'] === undefined) return false;
    return true;
}

export function StrikesFromJSON(json: any): Strikes {
    return StrikesFromJSONTyped(json, false);
}

export function StrikesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Strikes {
    if (json == null) {
        return json;
    }
    return {
        
        'call': json['call'],
        'put': json['put'],
    };
}

export function StrikesToJSON(json: any): Strikes {
    return StrikesToJSONTyped(json, false);
}

export function StrikesToJSONTyped(value?: Strikes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'call': value['call'],
        'put': value['put'],
    };
}

