/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token0Token1Composition
 */
export interface Token0Token1Composition {
    /**
     * Amount of token0
     * @type {string}
     * @memberof Token0Token1Composition
     */
    token0: string;
    /**
     * Amount of token1
     * @type {string}
     * @memberof Token0Token1Composition
     */
    token1: string;
}

/**
 * Check if a given object implements the Token0Token1Composition interface.
 */
export function instanceOfToken0Token1Composition(value: object): value is Token0Token1Composition {
    if (!('token0' in value) || value['token0'] === undefined) return false;
    if (!('token1' in value) || value['token1'] === undefined) return false;
    return true;
}

export function Token0Token1CompositionFromJSON(json: any): Token0Token1Composition {
    return Token0Token1CompositionFromJSONTyped(json, false);
}

export function Token0Token1CompositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token0Token1Composition {
    if (json == null) {
        return json;
    }
    return {
        
        'token0': json['token0'],
        'token1': json['token1'],
    };
}

export function Token0Token1CompositionToJSON(json: any): Token0Token1Composition {
    return Token0Token1CompositionToJSONTyped(json, false);
}

export function Token0Token1CompositionToJSONTyped(value?: Token0Token1Composition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token0': value['token0'],
        'token1': value['token1'],
    };
}

