/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenDto
 */
export interface TokenDto {
    /**
     * Address of the ERC20 token
     * @type {string}
     * @memberof TokenDto
     */
    address: string;
    /**
     * Decimals of the ERC20 token
     * @type {string}
     * @memberof TokenDto
     */
    decimals: string;
    /**
     * Symbol of the ERC20 token
     * @type {string}
     * @memberof TokenDto
     */
    symbol: string;
}

/**
 * Check if a given object implements the TokenDto interface.
 */
export function instanceOfTokenDto(value: object): value is TokenDto {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function TokenDtoFromJSON(json: any): TokenDto {
    return TokenDtoFromJSONTyped(json, false);
}

export function TokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'decimals': json['decimals'],
        'symbol': json['symbol'],
    };
}

export function TokenDtoToJSON(json: any): TokenDto {
    return TokenDtoToJSONTyped(json, false);
}

export function TokenDtoToJSONTyped(value?: TokenDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'decimals': value['decimals'],
        'symbol': value['symbol'],
    };
}

