/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenDto } from './TokenDto';
import {
    TokenDtoFromJSON,
    TokenDtoFromJSONTyped,
    TokenDtoToJSON,
    TokenDtoToJSONTyped,
} from './TokenDto';

/**
 * 
 * @export
 * @interface Token0Token1
 */
export interface Token0Token1 {
    /**
     * Token0 details and amount
     * @type {TokenDto}
     * @memberof Token0Token1
     */
    token0: TokenDto;
    /**
     * Token1 token details and amount
     * @type {TokenDto}
     * @memberof Token0Token1
     */
    token1: TokenDto;
}

/**
 * Check if a given object implements the Token0Token1 interface.
 */
export function instanceOfToken0Token1(value: object): value is Token0Token1 {
    if (!('token0' in value) || value['token0'] === undefined) return false;
    if (!('token1' in value) || value['token1'] === undefined) return false;
    return true;
}

export function Token0Token1FromJSON(json: any): Token0Token1 {
    return Token0Token1FromJSONTyped(json, false);
}

export function Token0Token1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Token0Token1 {
    if (json == null) {
        return json;
    }
    return {
        
        'token0': TokenDtoFromJSON(json['token0']),
        'token1': TokenDtoFromJSON(json['token1']),
    };
}

export function Token0Token1ToJSON(json: any): Token0Token1 {
    return Token0Token1ToJSONTyped(json, false);
}

export function Token0Token1ToJSONTyped(value?: Token0Token1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token0': TokenDtoToJSON(value['token0']),
        'token1': TokenDtoToJSON(value['token1']),
    };
}

