/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionData
 */
export interface TransactionData {
    /**
     * Address to send the transaction calldata to
     * @type {string}
     * @memberof TransactionData
     */
    to: string;
    /**
     * Transaction calldata
     * @type {string}
     * @memberof TransactionData
     */
    data: string;
}

/**
 * Check if a given object implements the TransactionData interface.
 */
export function instanceOfTransactionData(value: object): value is TransactionData {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TransactionDataFromJSON(json: any): TransactionData {
    return TransactionDataFromJSONTyped(json, false);
}

export function TransactionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionData {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'data': json['data'],
    };
}

export function TransactionDataToJSON(json: any): TransactionData {
    return TransactionDataToJSONTyped(json, false);
}

export function TransactionDataToJSONTyped(value?: TransactionData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'data': value['data'],
    };
}

