/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VestPositionsResponseDto } from './VestPositionsResponseDto';
import {
    VestPositionsResponseDtoFromJSON,
    VestPositionsResponseDtoFromJSONTyped,
    VestPositionsResponseDtoToJSON,
    VestPositionsResponseDtoToJSONTyped,
} from './VestPositionsResponseDto';

/**
 * 
 * @export
 * @interface UserXSykDataResponseDto
 */
export interface UserXSykDataResponseDto {
    /**
     * 
     * @type {string}
     * @memberof UserXSykDataResponseDto
     */
    readonly totalXSykAllocated: string;
    /**
     * 
     * @type {string}
     * @memberof UserXSykDataResponseDto
     */
    readonly totalSykPending: string;
    /**
     * 
     * @type {Array<VestPositionsResponseDto>}
     * @memberof UserXSykDataResponseDto
     */
    readonly positions: Array<VestPositionsResponseDto>;
}

/**
 * Check if a given object implements the UserXSykDataResponseDto interface.
 */
export function instanceOfUserXSykDataResponseDto(value: object): value is UserXSykDataResponseDto {
    if (!('totalXSykAllocated' in value) || value['totalXSykAllocated'] === undefined) return false;
    if (!('totalSykPending' in value) || value['totalSykPending'] === undefined) return false;
    if (!('positions' in value) || value['positions'] === undefined) return false;
    return true;
}

export function UserXSykDataResponseDtoFromJSON(json: any): UserXSykDataResponseDto {
    return UserXSykDataResponseDtoFromJSONTyped(json, false);
}

export function UserXSykDataResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserXSykDataResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalXSykAllocated': json['totalXSykAllocated'],
        'totalSykPending': json['totalSykPending'],
        'positions': ((json['positions'] as Array<any>).map(VestPositionsResponseDtoFromJSON)),
    };
}

export function UserXSykDataResponseDtoToJSON(json: any): UserXSykDataResponseDto {
    return UserXSykDataResponseDtoToJSONTyped(json, false);
}

export function UserXSykDataResponseDtoToJSONTyped(value?: Omit<UserXSykDataResponseDto, 'totalXSykAllocated'|'totalSykPending'|'positions'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

