/* tslint:disable */
/* eslint-disable */
/**
 * Stryke API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VestPositionsResponseDto
 */
export interface VestPositionsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof VestPositionsResponseDto
     */
    readonly account: string;
    /**
     * 
     * @type {number}
     * @memberof VestPositionsResponseDto
     */
    readonly duration: number;
    /**
     * 
     * @type {string}
     * @memberof VestPositionsResponseDto
     */
    readonly xSykAmount: string;
    /**
     * 
     * @type {string}
     * @memberof VestPositionsResponseDto
     */
    readonly sykAmount: string;
    /**
     * 
     * @type {string}
     * @memberof VestPositionsResponseDto
     */
    readonly vestIndex: string;
    /**
     * 
     * @type {number}
     * @memberof VestPositionsResponseDto
     */
    readonly blockTimestamp: number;
    /**
     * 
     * @type {string}
     * @memberof VestPositionsResponseDto
     */
    readonly transactionHash: string;
}

/**
 * Check if a given object implements the VestPositionsResponseDto interface.
 */
export function instanceOfVestPositionsResponseDto(value: object): value is VestPositionsResponseDto {
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('xSykAmount' in value) || value['xSykAmount'] === undefined) return false;
    if (!('sykAmount' in value) || value['sykAmount'] === undefined) return false;
    if (!('vestIndex' in value) || value['vestIndex'] === undefined) return false;
    if (!('blockTimestamp' in value) || value['blockTimestamp'] === undefined) return false;
    if (!('transactionHash' in value) || value['transactionHash'] === undefined) return false;
    return true;
}

export function VestPositionsResponseDtoFromJSON(json: any): VestPositionsResponseDto {
    return VestPositionsResponseDtoFromJSONTyped(json, false);
}

export function VestPositionsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VestPositionsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'],
        'duration': json['duration'],
        'xSykAmount': json['xSykAmount'],
        'sykAmount': json['sykAmount'],
        'vestIndex': json['vestIndex'],
        'blockTimestamp': json['blockTimestamp'],
        'transactionHash': json['transactionHash'],
    };
}

export function VestPositionsResponseDtoToJSON(json: any): VestPositionsResponseDto {
    return VestPositionsResponseDtoToJSONTyped(json, false);
}

export function VestPositionsResponseDtoToJSONTyped(value?: Omit<VestPositionsResponseDto, 'account'|'duration'|'xSykAmount'|'sykAmount'|'vestIndex'|'blockTimestamp'|'transactionHash'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

